FROM postgres:18-bookworm

# Install PostGIS extension
RUN apt-get update && apt-get install -y \
    postgresql-18-postgis-3 \
    postgresql-18-postgis-3-scripts \
    && rm -rf /var/lib/apt/lists/*

EXPOSE 5432
