-- 20260315_geocoding_job_runs.sql
-- Purpose: Persist geocoding job history for operator visibility and auditing.

CREATE TABLE IF NOT EXISTS app.geocoding_job_runs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider text NOT NULL,
  mode text NOT NULL,
  precision smallint NOT NULL,
  limit_rows integer NOT NULL,
  per_minute integer NOT NULL,
  permanent boolean NOT NULL DEFAULT false,
  status text NOT NULL,
  processed integer,
  successful integer,
  poi_hits integer,
  rate_limited integer,
  duration_ms integer,
  error text,
  started_at timestamp with time zone NOT NULL DEFAULT now(),
  finished_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT geocoding_job_runs_status_check
    CHECK (status IN ('running', 'completed', 'failed'))
);

CREATE INDEX IF NOT EXISTS idx_geocoding_job_runs_started_at
  ON app.geocoding_job_runs (started_at DESC);

GRANT SELECT, INSERT, UPDATE ON TABLE app.geocoding_job_runs TO shadowcheck_user;
GRANT USAGE, SELECT ON SEQUENCE app.geocoding_job_runs_id_seq TO shadowcheck_user;
