-- Migration: 20260614_054_sibling_group_scope.sql
-- STATUS: SUPERSEDED BEFORE APPLICATION TO shadowcheck_db
--
-- Original intent: add sibling_group_id (FK → network_sibling_pairs.id) to
-- network_notes and network_media so that notes/media could be "scoped" to a
-- sibling group.
--
-- Why this was rejected:
--   network_sibling_pairs.id is an edge-row handle, not a physical-box/component
--   identifier. Storing sibling_group_id → pair-edge on a media record conflates
--   edge membership with component ownership, muddying evidence provenance.
--
--   The approved model is:
--     media → observation_id  (precise anchor, from _052)
--     media → bssid           (fallback anchor, existing)
--   Discovery across the physical component is handled by the view layer
--   (v_sibling_group_media, _055), which routes through app.mv_sibling_groups
--   (connected-component MV) rather than through pair-edge IDs.
--
-- This migration is intentionally a no-op so the ledger can be stamped and
-- the runner proceeds to _055 without DDL side-effects.

-- (intentional no-op)
SELECT 1;
