/**
 * Canonical API endpoint registry for the Admin API Testing tab.
 *
 * Every new backend route MUST get an entry here before the PR is merged.
 * The ApiTestingTab renders entirely from this config — there is no hardcoded markup.
 */

type HttpMethod = 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE';

export interface ApiInput {
  name: string;
  label: string;
  defaultValue?: string;
  placeholder?: string;
  type?: 'text' | 'number' | 'select';
  options?: string[];
}

export interface ApiEndpointConfig {
  category: string;
  label: string;
  description?: string;
  method: HttpMethod;
  path: string;
  params?: ApiInput[];
  requiresAuth?: boolean;
  defaultBody?: string;
}

export type { HttpMethod };

export const API_ENDPOINTS: ApiEndpointConfig[] = [
  // ── Health & Core ─────────────────────────────────────────────────────────
  { category: 'Health & Core', label: 'Health', path: '/health', method: 'GET' },
  { category: 'Health & Core', label: 'API Health', path: '/api/health', method: 'GET' },
  {
    category: 'Health & Core',
    label: 'App Settings (AWS)',
    path: '/api/settings/aws',
    method: 'GET',
  },
  {
    category: 'Health & Core',
    label: 'Update Settings (AWS)',
    path: '/api/settings/aws',
    method: 'POST',
    requiresAuth: true,
    defaultBody: '{\n  "region": "us-east-1"\n}',
  },
  {
    category: 'Health & Core',
    label: 'Reload Secrets',
    path: '/api/settings/reload-secrets',
    method: 'POST',
    requiresAuth: true,
  },
  {
    category: 'Health & Core',
    label: 'Settings Inventory',
    path: '/api/settings/list',
    method: 'GET',
  },
  {
    category: 'Health & Core',
    label: 'WiGLE Settings',
    path: '/api/settings/wigle',
    method: 'GET',
    requiresAuth: true,
  },
  {
    category: 'Health & Core',
    label: 'WiGLE Settings Update',
    path: '/api/settings/wigle',
    method: 'POST',
    requiresAuth: true,
    defaultBody: '{\n  "api_name": "",\n  "api_token": ""\n}',
  },
  {
    category: 'Health & Core',
    label: 'WiGLE Settings Test',
    path: '/api/settings/wigle/test',
    method: 'GET',
    requiresAuth: true,
  },
  {
    category: 'Health & Core',
    label: 'Mapbox Settings',
    path: '/api/settings/mapbox',
    method: 'GET',
    requiresAuth: true,
  },
  {
    category: 'Health & Core',
    label: 'Mapbox Settings Update',
    path: '/api/settings/mapbox',
    method: 'POST',
    requiresAuth: true,
    defaultBody: '{\n  "label": "default",\n  "token": "pk.eyJ1..."\n}',
  },
  {
    category: 'Health & Core',
    label: 'Mapbox Settings Delete',
    path: '/api/settings/mapbox/:label',
    method: 'DELETE',
    requiresAuth: true,
    params: [{ name: 'label', label: 'Label', placeholder: 'default' }],
  },
  {
    category: 'Health & Core',
    label: 'Smarty Settings',
    path: '/api/settings/smarty',
    method: 'GET',
    requiresAuth: true,
  },
  {
    category: 'Health & Core',
    label: 'Smarty Settings Update',
    path: '/api/settings/smarty',
    method: 'POST',
    requiresAuth: true,
    defaultBody: '{\n  "auth_id": "",\n  "auth_token": ""\n}',
  },

  // ── Auth ──────────────────────────────────────────────────────────────────
  { category: 'Auth', label: 'Auth Me', path: '/api/auth/me', method: 'GET', requiresAuth: true },
  {
    category: 'Auth',
    label: 'Auth Login',
    path: '/api/auth/login',
    method: 'POST',
    defaultBody: '{\n  "username": "admin",\n  "password": ""\n}',
  },
  {
    category: 'Auth',
    label: 'Auth Logout',
    path: '/api/auth/logout',
    method: 'POST',
    requiresAuth: true,
  },
  {
    category: 'Auth',
    label: 'Auth Change Password',
    path: '/api/auth/change-password',
    method: 'POST',
    requiresAuth: true,
    defaultBody: '{\n  "currentPassword": "",\n  "newPassword": ""\n}',
  },

  // ── Public Reference ──────────────────────────────────────────────────────
  {
    category: 'Public Reference',
    label: 'Agency Offices',
    path: '/agency-offices',
    method: 'GET',
  },
  {
    category: 'Public Reference',
    label: 'Agency Offices Count',
    path: '/agency-offices/count',
    method: 'GET',
  },
  {
    category: 'Public Reference',
    label: 'Federal Courthouses',
    path: '/federal-courthouses',
    method: 'GET',
  },
  {
    category: 'Surveillance',
    label: 'DeFlock Cameras',
    description: 'GeoJSON FeatureCollection of Flock Safety ALPR camera locations',
    path: '/api/v1/surveillance/deflock-cameras',
    method: 'GET',
  },
  {
    category: 'Surveillance',
    label: 'ShotSpotter Zones',
    description:
      'GeoJSON FeatureCollection of ShotSpotter acoustic gunshot detection coverage zones',
    path: '/api/v1/surveillance/shotspotter-zones',
    method: 'GET',
  },
  {
    category: 'Surveillance',
    label: 'BWC Detections',
    description:
      'Body-worn camera detections (Axon, Motorola) from surveillance scan — filter via bwc=true',
    path: '/api/networks?bwc=true',
    method: 'GET',
  },
  {
    category: 'Surveillance',
    label: 'ShotSpotter Sensors',
    description: 'GeoJSON FeatureCollection of ShotSpotter sensor locations (WIRED 2024 leak)',
    path: '/api/v1/surveillance/shotspotter-sensors',
    method: 'GET',
  },

  // ── Geospatial ────────────────────────────────────────────────────────────
  { category: 'Geospatial', label: 'Mapbox Token', path: '/api/mapbox-token', method: 'GET' },
  {
    category: 'Geospatial',
    label: 'Mapbox Style',
    path: '/api/mapbox-style',
    method: 'GET',
    params: [{ name: 'style', label: 'Style', defaultValue: 'satellite' }],
  },
  {
    category: 'Geospatial',
    label: 'Mapbox Proxy',
    path: '/api/mapbox-proxy',
    method: 'GET',
    params: [{ name: 'url', label: 'Mapbox URL', placeholder: 'mapbox://styles/...' }],
  },
  {
    category: 'Geospatial',
    label: 'Google Maps Token',
    path: '/api/google-maps-token',
    method: 'GET',
  },
  { category: 'Geospatial', label: 'Home Location', path: '/api/home-location', method: 'GET' },
  {
    category: 'Geospatial',
    label: 'Location Markers',
    path: '/api/location-markers',
    method: 'GET',
  },
  {
    category: 'Geospatial',
    label: 'Home Marker',
    path: '/api/location-markers/home',
    method: 'GET',
  },
  {
    category: 'Geospatial',
    label: 'Set Home Marker',
    path: '/api/location-markers/home',
    method: 'POST',
    requiresAuth: true,
    defaultBody: '{\n  "lat": 38.9,\n  "lon": -77.0\n}',
  },
  {
    category: 'Geospatial',
    label: 'Delete Home Marker',
    path: '/api/location-markers/home',
    method: 'DELETE',
    requiresAuth: true,
  },
  {
    category: 'Geospatial',
    label: 'Add Location Marker',
    path: '/api/location-markers',
    method: 'POST',
    requiresAuth: true,
    defaultBody: '{\n  "lat": 38.9,\n  "lon": -77.0,\n  "label": ""\n}',
  },
  {
    category: 'Geospatial',
    label: 'Delete Location Marker',
    path: '/api/location-markers/:id',
    method: 'DELETE',
    requiresAuth: true,
    params: [{ name: 'id', label: 'Marker ID', placeholder: '1', type: 'number' }],
  },
  {
    category: 'Geospatial',
    label: 'Admin Home Location',
    path: '/api/admin/home-location',
    method: 'GET',
    requiresAuth: true,
  },
  {
    category: 'Geospatial',
    label: 'Admin Set Home Location',
    path: '/api/admin/home-location',
    method: 'POST',
    requiresAuth: true,
    defaultBody: '{\n  "lat": 38.9,\n  "lon": -77.0\n}',
  },
  {
    category: 'Geospatial',
    label: 'Geocode Address',
    path: '/api/geocode',
    method: 'POST',
    requiresAuth: true,
    defaultBody: '{\n  "address": "1600 Pennsylvania Ave NW, Washington DC"\n}',
  },

  // ── Explorer (legacy list + platinum single-network) ─────────────────────
  {
    category: 'Explorer',
    label: 'Explorer Networks',
    path: '/api/explorer/networks',
    method: 'GET',
    params: [
      { name: 'limit', label: 'Limit', defaultValue: '50', type: 'number' },
      { name: 'offset', label: 'Offset', defaultValue: '0', type: 'number' },
    ],
  },
  {
    category: 'Explorer',
    label: 'Explorer Networks v2',
    path: '/api/explorer/networks-v2',
    method: 'GET',
    params: [
      { name: 'limit', label: 'Limit', defaultValue: '50', type: 'number' },
      { name: 'offset', label: 'Offset', defaultValue: '0', type: 'number' },
    ],
  },
  {
    category: 'Explorer',
    label: 'Explorer Network (single)',
    path: '/api/explorer/network/:bssid',
    method: 'GET',
    params: [{ name: 'bssid', label: 'BSSID', placeholder: '00:11:22:33:44:55' }],
  },

  // ── Networks v1 ───────────────────────────────────────────────────────────
  {
    category: 'Networks v1',
    label: 'Networks List',
    path: '/api/networks',
    method: 'GET',
    params: [
      { name: 'limit', label: 'Limit', defaultValue: '50', type: 'number' },
      { name: 'offset', label: 'Offset', defaultValue: '0', type: 'number' },
    ],
  },
  {
    category: 'Networks v1',
    label: 'Network Observations',
    path: '/api/networks/observations/:bssid',
    method: 'GET',
    params: [{ name: 'bssid', label: 'BSSID', placeholder: '00:11:22:33:44:55' }],
  },
  {
    category: 'Networks v1',
    label: 'Network Search by SSID',
    path: '/api/networks/search/:ssid',
    method: 'GET',
    params: [{ name: 'ssid', label: 'SSID', placeholder: 'Starbucks' }],
  },
  {
    category: 'Networks v1',
    label: 'Tagged Networks',
    path: '/api/networks/tagged',
    method: 'GET',
  },
  {
    category: 'Networks v1',
    label: 'Network WiGLE Observations',
    path: '/api/networks/:bssid/wigle-observations',
    method: 'GET',
    params: [{ name: 'bssid', label: 'BSSID', placeholder: '00:11:22:33:44:55' }],
  },
  {
    category: 'Networks v1',
    label: 'WiGLE Observations Batch',
    path: '/api/networks/wigle-observations/batch',
    method: 'POST',
    requiresAuth: true,
    defaultBody: '{\n  "bssids": ["00:11:22:33:44:55"]\n}',
  },
  {
    category: 'Networks v1',
    label: 'Network Notes',
    path: '/api/networks/:bssid/notes',
    method: 'GET',
    params: [{ name: 'bssid', label: 'BSSID', placeholder: '00:11:22:33:44:55' }],
  },
  {
    category: 'Networks v1',
    label: 'Add Network Note',
    path: '/api/networks/:bssid/notes',
    method: 'POST',
    requiresAuth: true,
    params: [{ name: 'bssid', label: 'BSSID', placeholder: '00:11:22:33:44:55' }],
    defaultBody: '{\n  "note": ""\n}',
  },
  {
    category: 'Networks v1',
    label: 'Update Network Note',
    path: '/api/networks/:bssid/notes/:noteId',
    method: 'PATCH',
    requiresAuth: true,
    params: [
      { name: 'bssid', label: 'BSSID', placeholder: '00:11:22:33:44:55' },
      { name: 'noteId', label: 'Note ID', placeholder: '1', type: 'number' },
    ],
    defaultBody: '{\n  "note": ""\n}',
  },
  {
    category: 'Networks v1',
    label: 'Delete Network Note',
    path: '/api/networks/:bssid/notes/:noteId',
    method: 'DELETE',
    requiresAuth: true,
    params: [
      { name: 'bssid', label: 'BSSID', placeholder: '00:11:22:33:44:55' },
      { name: 'noteId', label: 'Note ID', placeholder: '1', type: 'number' },
    ],
  },
  {
    category: 'Networks v1',
    label: 'Manufacturer by BSSID',
    path: '/api/manufacturer/:bssid',
    method: 'GET',
    params: [{ name: 'bssid', label: 'BSSID', placeholder: '00:11:22:33:44:55' }],
  },
  {
    category: 'Networks v1',
    label: 'Networks by Manufacturer',
    path: '/api/manufacturer/:bssid/networks',
    method: 'GET',
    params: [{ name: 'bssid', label: 'BSSID/OUI prefix', placeholder: '00:11:22:33:44:55' }],
  },
  {
    category: 'Networks v1',
    label: 'Nearest Agencies',
    path: '/api/networks/nearest-agencies/:bssid',
    method: 'GET',
    params: [{ name: 'bssid', label: 'BSSID', placeholder: '00:11:22:33:44:55' }],
  },
  {
    category: 'Networks v1',
    label: 'Nearest Agencies Batch',
    path: '/api/networks/nearest-agencies/batch',
    method: 'POST',
    requiresAuth: true,
    defaultBody: '{\n  "bssids": ["00:11:22:33:44:55"]\n}',
  },

  // ── Network Tags ──────────────────────────────────────────────────────────
  {
    category: 'Network Tags',
    label: 'List All Tags',
    path: '/api/network-tags/',
    method: 'GET',
    requiresAuth: true,
    params: [
      { name: 'limit', label: 'Limit', defaultValue: '50', type: 'number' },
      { name: 'offset', label: 'Offset', defaultValue: '0', type: 'number' },
    ],
  },
  {
    category: 'Network Tags',
    label: 'Tags for BSSID',
    path: '/api/network-tags/:bssid',
    method: 'GET',
    requiresAuth: true,
    params: [{ name: 'bssid', label: 'BSSID', placeholder: '00:11:22:33:44:55' }],
  },
  {
    category: 'Network Tags',
    label: 'Create Tag',
    path: '/api/network-tags/:bssid',
    method: 'POST',
    requiresAuth: true,
    params: [{ name: 'bssid', label: 'BSSID', placeholder: '00:11:22:33:44:55' }],
    defaultBody: '{\n  "threat_tag": "SUSPECT",\n  "threat_confidence": 0.7\n}',
  },
  {
    category: 'Network Tags',
    label: 'Ignore Network',
    path: '/api/network-tags/:bssid/ignore',
    method: 'PATCH',
    requiresAuth: true,
    params: [{ name: 'bssid', label: 'BSSID', placeholder: '00:11:22:33:44:55' }],
    defaultBody: '{\n  "is_ignored": true\n}',
  },
  {
    category: 'Network Tags',
    label: 'Tag Notes',
    path: '/api/network-tags/:bssid/notes',
    method: 'PATCH',
    requiresAuth: true,
    params: [{ name: 'bssid', label: 'BSSID', placeholder: '00:11:22:33:44:55' }],
    defaultBody: '{\n  "notes": ""\n}',
  },
  {
    category: 'Network Tags',
    label: 'Tag Investigate',
    path: '/api/network-tags/:bssid/investigate',
    method: 'PATCH',
    requiresAuth: true,
    params: [{ name: 'bssid', label: 'BSSID', placeholder: '00:11:22:33:44:55' }],
    defaultBody: '{\n  "investigate": true\n}',
  },
  {
    category: 'Network Tags',
    label: 'Delete Tag',
    path: '/api/network-tags/:bssid',
    method: 'DELETE',
    requiresAuth: true,
    params: [{ name: 'bssid', label: 'BSSID', placeholder: '00:11:22:33:44:55' }],
  },
  {
    category: 'Network Tags',
    label: 'Export Tags for ML',
    path: '/api/network-tags/export/ml',
    method: 'GET',
    requiresAuth: true,
  },

  // ── Networks v2 ───────────────────────────────────────────────────────────
  {
    category: 'Networks v2',
    label: 'Networks List (v2)',
    path: '/api/v2/networks',
    method: 'GET',
    params: [
      { name: 'limit', label: 'Limit', defaultValue: '10', type: 'number' },
      { name: 'offset', label: 'Offset', defaultValue: '0', type: 'number' },
      { name: 'search', label: 'Search', placeholder: 'SSID/BSSID' },
      {
        name: 'sort',
        label: 'Sort',
        defaultValue: 'observed_at',
        type: 'select',
        options: ['observed_at', 'signal', 'threat_score', 'observations'],
      },
    ],
  },
  {
    category: 'Networks v2',
    label: 'Network Details (v2)',
    path: '/api/v2/networks/:bssid',
    method: 'GET',
    params: [{ name: 'bssid', label: 'BSSID', placeholder: '00:11:22:33:44:55' }],
  },
  {
    category: 'Networks v2',
    label: 'Dashboard Metrics (v2)',
    path: '/api/v2/dashboard/metrics',
    method: 'GET',
  },
  {
    category: 'Networks v2',
    label: 'Universal Filter: List',
    path: '/api/v2/networks/filtered',
    method: 'GET',
    params: [
      { name: 'limit', label: 'Limit', defaultValue: '10', type: 'number' },
      { name: 'filters', label: 'Filters (JSON)', defaultValue: '{"ssid":""}' },
      { name: 'enabled', label: 'Enabled (JSON)', defaultValue: '{"ssid":false}' },
    ],
  },
  {
    category: 'Networks v2',
    label: 'Universal Filter: Geo',
    path: '/api/v2/networks/filtered/geospatial',
    method: 'GET',
    params: [
      { name: 'limit', label: 'Limit', defaultValue: '100', type: 'number' },
      { name: 'filters', label: 'Filters (JSON)', defaultValue: '{}' },
      { name: 'enabled', label: 'Enabled (JSON)', defaultValue: '{}' },
    ],
  },
  {
    category: 'Networks v2',
    label: 'Universal Filter: Observations',
    path: '/api/v2/networks/filtered/observations',
    method: 'GET',
    params: [
      { name: 'limit', label: 'Limit', defaultValue: '100', type: 'number' },
      { name: 'filters', label: 'Filters (JSON)', defaultValue: '{}' },
      { name: 'enabled', label: 'Enabled (JSON)', defaultValue: '{}' },
    ],
  },
  {
    category: 'Networks v2',
    label: 'Universal Filter: Debug',
    path: '/api/v2/networks/filtered/debug',
    method: 'GET',
    params: [
      { name: 'filters', label: 'Filters (JSON)', defaultValue: '{}' },
      { name: 'enabled', label: 'Enabled (JSON)', defaultValue: '{}' },
    ],
  },

  // ── Threats & Analytics ───────────────────────────────────────────────────
  {
    category: 'Threats & Analytics',
    label: 'Threat Map (v2)',
    path: '/api/v2/threats/map',
    method: 'GET',
    params: [
      { name: 'days', label: 'Days', defaultValue: '30', type: 'number' },
      {
        name: 'severity',
        label: 'Severity',
        defaultValue: 'all',
        type: 'select',
        options: ['all', 'critical', 'high', 'med', 'low'],
      },
    ],
  },
  {
    category: 'Threats & Analytics',
    label: 'Threat Severity Counts',
    path: '/api/v2/threats/severity-counts',
    method: 'GET',
  },
  {
    category: 'Threats & Analytics',
    label: 'Threats Quick',
    path: '/api/threats/quick',
    method: 'GET',
  },
  {
    category: 'Threats & Analytics',
    label: 'Threat Detection (v1)',
    path: '/api/threats/detect',
    method: 'GET',
  },
  {
    category: 'Threats & Analytics',
    label: 'Dashboard Metrics (v1)',
    path: '/api/dashboard/metrics',
    method: 'GET',
  },
  {
    category: 'Threats & Analytics',
    label: 'Dashboard Threats (v1)',
    path: '/api/dashboard/threats',
    method: 'GET',
  },
  {
    category: 'Threats & Analytics',
    label: 'Dashboard Summary (v1)',
    path: '/api/dashboard/summary',
    method: 'GET',
  },
  {
    category: 'Threats & Analytics',
    label: 'Set Network Tag',
    path: '/api/network-tags/:bssid/threat',
    method: 'PATCH',
    requiresAuth: true,
    params: [
      { name: 'bssid', label: 'BSSID', placeholder: '00:11:22...' },
      {
        name: 'threat_tag',
        label: 'Tag',
        defaultValue: 'SUSPECT',
        type: 'select',
        options: ['THREAT', 'SUSPECT', 'FALSE_POSITIVE', 'INVESTIGATE'],
      },
    ],
    defaultBody: '{\n  "threat_tag": "SUSPECT",\n  "threat_confidence": 0.7\n}',
  },
  {
    category: 'Threats & Analytics',
    label: 'Analytics: Filtered',
    path: '/api/v2/networks/filtered/analytics',
    method: 'GET',
    params: [
      { name: 'filters', label: 'Filters (JSON)', defaultValue: '{}' },
      { name: 'enabled', label: 'Enabled (JSON)', defaultValue: '{}' },
    ],
  },
  {
    category: 'Threats & Analytics',
    label: 'Analytics: Legacy Dashboard',
    path: '/api/analytics/dashboard',
    method: 'GET',
  },
  {
    category: 'Threats & Analytics',
    label: 'Analytics: Network Types',
    path: '/api/analytics/network-types',
    method: 'GET',
  },
  {
    category: 'Threats & Analytics',
    label: 'Analytics: Signal Strength',
    path: '/api/analytics/signal-strength',
    method: 'GET',
  },
  {
    category: 'Threats & Analytics',
    label: 'Analytics: Temporal Activity',
    path: '/api/analytics/temporal-activity',
    method: 'GET',
  },
  {
    category: 'Threats & Analytics',
    label: 'Analytics: Radio Type Over Time',
    path: '/api/analytics/radio-type-over-time',
    method: 'GET',
  },
  {
    category: 'Threats & Analytics',
    label: 'Analytics: Security',
    path: '/api/analytics/security',
    method: 'GET',
  },
  {
    category: 'Threats & Analytics',
    label: 'Analytics: Top Networks',
    path: '/api/analytics/top-networks',
    method: 'GET',
  },
  {
    category: 'Threats & Analytics',
    label: 'Analytics: Bulk',
    path: '/api/analytics/bulk',
    method: 'GET',
  },
  {
    category: 'Threats & Analytics',
    label: 'Analytics: Threat Distribution',
    path: '/api/analytics/threat-distribution',
    method: 'GET',
  },
  {
    category: 'Threats & Analytics',
    label: 'Analytics: Threat Trends',
    path: '/api/analytics/threat-trends',
    method: 'GET',
  },
  {
    category: 'Threats & Analytics',
    label: 'Threat Report',
    path: '/api/reports/threat/:bssid',
    method: 'GET',
    params: [{ name: 'bssid', label: 'BSSID', placeholder: '00:11:22:33:44:55' }],
  },

  // ── WiGLE ─────────────────────────────────────────────────────────────────
  { category: 'WiGLE', label: 'WiGLE Status', path: '/api/wigle/api-status', method: 'GET' },
  {
    category: 'WiGLE',
    label: 'WiGLE Quota Status',
    path: '/api/wigle/quota-status',
    method: 'GET',
    requiresAuth: true,
  },
  {
    category: 'WiGLE',
    label: 'WiGLE Quota Reset',
    path: '/api/wigle/quota-reset',
    method: 'POST',
    requiresAuth: true,
  },
  {
    category: 'WiGLE',
    label: 'WiGLE Search',
    path: '/api/wigle/search',
    method: 'GET',
    params: [
      { name: 'ssid', label: 'SSID', placeholder: 'Network Name' },
      { name: 'bssid', label: 'BSSID', placeholder: '00:11:22...' },
    ],
  },
  {
    category: 'WiGLE',
    label: 'WiGLE DB Network',
    path: '/api/wigle/network/:bssid',
    method: 'GET',
    params: [{ name: 'bssid', label: 'BSSID', placeholder: '00:11:22:33:44:55' }],
  },
  {
    category: 'WiGLE',
    label: 'WiGLE DB Page (netid)',
    path: '/api/wigle/page/network/:netid',
    method: 'GET',
    params: [{ name: 'netid', label: 'Network ID', placeholder: '00:11:22:33:44:55' }],
  },
  {
    category: 'WiGLE',
    label: 'WiGLE DB Networks v2',
    path: '/api/wigle/networks-v2',
    method: 'GET',
    params: [
      { name: 'limit', label: 'Limit', defaultValue: '50', type: 'number' },
      { name: 'offset', label: 'Offset', defaultValue: '0', type: 'number' },
    ],
  },
  {
    category: 'WiGLE',
    label: 'WiGLE DB Networks v3',
    path: '/api/wigle/networks-v3',
    method: 'GET',
    params: [
      { name: 'limit', label: 'Limit', defaultValue: '50', type: 'number' },
      { name: 'offset', label: 'Offset', defaultValue: '0', type: 'number' },
    ],
  },
  {
    category: 'WiGLE',
    label: 'WiGLE KML Points',
    path: '/api/wigle/kml-points',
    method: 'GET',
    params: [
      { name: 'limit', label: 'Limit', defaultValue: '100', type: 'number' },
      { name: 'offset', label: 'Offset', defaultValue: '0', type: 'number' },
    ],
  },
  {
    category: 'WiGLE',
    label: 'WiGLE DB Observations (netid)',
    path: '/api/wigle/observations/:netid',
    method: 'GET',
    params: [{ name: 'netid', label: 'Network ID', placeholder: '00:11:22:33:44:55' }],
  },
  {
    category: 'WiGLE',
    label: 'WiGLE Live Lookup',
    path: '/api/wigle/live/:bssid',
    method: 'GET',
    params: [{ name: 'bssid', label: 'BSSID', placeholder: '00:11:22:33:44:55' }],
  },
  {
    category: 'WiGLE',
    label: 'WiGLE Batch Detail & Import',
    path: '/api/wigle/detail/batch',
    method: 'POST',
    params: [],
    defaultBody: '{\n  "bssids": ["00:11:22:33:44:55", "AA:BB:CC:DD:EE:FF"],\n  "import": true\n}',
  },
  {
    category: 'WiGLE',
    label: 'WiGLE Detail & Import',
    path: '/api/wigle/detail/:netid',
    method: 'POST',
    params: [
      { name: 'netid', label: 'Network ID', placeholder: '00:11:22:33:44:55' },
      {
        name: 'import',
        label: 'Import?',
        defaultValue: 'false',
        type: 'select',
        options: ['true', 'false'],
      },
    ],
    defaultBody: '{\n  "import": false\n}',
  },
  {
    category: 'WiGLE',
    label: 'WiGLE BT Detail & Import',
    path: '/api/wigle/detail/bt/:netid',
    method: 'POST',
    params: [
      { name: 'netid', label: 'BT Network ID', placeholder: 'EC:81:93:76:BD:CE' },
      {
        name: 'import',
        label: 'Import?',
        defaultValue: 'false',
        type: 'select',
        options: ['true', 'false'],
      },
    ],
    defaultBody: '{\n  "import": false\n}',
  },
  {
    category: 'WiGLE',
    label: 'WiGLE User Stats',
    path: '/api/wigle/user-stats',
    method: 'GET',
  },
  {
    category: 'WiGLE',
    label: 'WiGLE Request Ledger',
    path: '/api/wigle/ledger',
    method: 'GET',
    params: [
      { name: 'limit', defaultValue: '50', placeholder: '50' },
      {
        name: 'status',
        defaultValue: 'all',
        placeholder: 'all|success|error|rate_limited|skipped',
      },
      { name: 'source', defaultValue: 'all', placeholder: 'all|import|event' },
    ],
  },
  {
    category: 'WiGLE',
    label: 'WiGLE Import Runs',
    path: '/api/wigle/search-api/import-runs',
    method: 'GET',
    params: [
      { name: 'limit', label: 'Limit', defaultValue: '100', type: 'number' },
      { name: 'page', label: 'Page', defaultValue: '1', type: 'number' },
      { name: 'status', label: 'Status', placeholder: 'running|paused|failed|completed|cancelled' },
      { name: 'sortBy', label: 'Sort By', placeholder: 'started_at,rows_inserted,status' },
      { name: 'sortDir', label: 'Sort Dir', placeholder: 'desc,asc' },
    ],
  },
  {
    category: 'WiGLE',
    label: 'Delete Import Run',
    description: 'Hard-delete a completed, cancelled, or failed import run by ID.',
    path: '/api/wigle/search-api/import-runs/:id',
    method: 'DELETE',
    params: [{ name: 'id', label: 'Run ID', placeholder: '123', type: 'number' }],
  },
  {
    category: 'WiGLE',
    label: 'V3 Enrichment Catalog',
    description:
      'Browse v2 search catalog with per-BSSID v3 enrichment stats. Supports server-side multi-column sort.',
    path: '/api/wigle/enrichment/catalog',
    method: 'GET',
    requiresAuth: true,
    params: [
      { name: 'page', label: 'Page', defaultValue: '1', type: 'number' },
      { name: 'limit', label: 'Limit', defaultValue: '50', type: 'number' },
      { name: 'ssid', label: 'SSID Filter', placeholder: 'partial match' },
      { name: 'bssid', label: 'BSSID Filter', placeholder: 'prefix match' },
      { name: 'city', label: 'City Filter', placeholder: 'partial match' },
      { name: 'region', label: 'Region', placeholder: 'DC' },
      { name: 'sortBy', label: 'Sort By', placeholder: 'lasttime,ssid,status' },
      { name: 'sortDir', label: 'Sort Dir', placeholder: 'desc,asc' },
    ],
  },
  {
    category: 'WiGLE',
    label: 'WiGLE Import Completeness',
    path: '/api/wigle/search-api/import-runs/completeness/summary',
    method: 'GET',
  },
  {
    category: 'WiGLE',
    label: 'WiGLE Resume Latest',
    path: '/api/wigle/search-api/import-runs/resume-latest',
    method: 'POST',
  },
  {
    category: 'WiGLE',
    label: 'WiGLE Import Run (single)',
    path: '/api/wigle/search-api/import-runs/:id',
    method: 'GET',
    params: [{ name: 'id', label: 'Run ID', placeholder: '1', type: 'number' }],
  },
  {
    category: 'WiGLE',
    label: 'WiGLE Resumable Latest',
    path: '/api/wigle/search-api/import-runs/resumable/latest',
    method: 'GET',
  },
  {
    category: 'WiGLE',
    label: 'Resume Import Run',
    path: '/api/wigle/search-api/import-runs/:id/resume',
    method: 'POST',
    requiresAuth: true,
    params: [{ name: 'id', label: 'Run ID', placeholder: '1', type: 'number' }],
  },
  {
    category: 'WiGLE',
    label: 'Pause Import Run',
    path: '/api/wigle/search-api/import-runs/:id/pause',
    method: 'POST',
    requiresAuth: true,
    params: [{ name: 'id', label: 'Run ID', placeholder: '1', type: 'number' }],
  },
  {
    category: 'WiGLE',
    label: 'Cancel Import Run',
    path: '/api/wigle/search-api/import-runs/:id/cancel',
    method: 'POST',
    requiresAuth: true,
    params: [{ name: 'id', label: 'Run ID', placeholder: '1', type: 'number' }],
  },
  {
    category: 'WiGLE',
    label: 'Import All (Search API)',
    path: '/api/wigle/search-api/import-all',
    method: 'POST',
    requiresAuth: true,
  },
  {
    category: 'WiGLE',
    label: 'BT/BLE Import Start',
    description: 'Start or resume a paginated BT/BLE import from WiGLE /api/v2/bluetooth/search',
    path: '/api/wigle/search-api/bt-import-start',
    method: 'POST',
    requiresAuth: true,
    defaultBody:
      '{\n  "country": "US",\n  "mfgrIdMinimum": 2504,\n  "mfgrIdMaximum": 2504,\n  "showBt": true,\n  "showBle": true\n}',
  },
  {
    category: 'WiGLE',
    label: 'Cluster Cleanup',
    path: '/api/wigle/search-api/import-runs/cluster-cleanup',
    method: 'DELETE',
    requiresAuth: true,
  },
  {
    category: 'WiGLE',
    label: 'Saved SSID Terms',
    path: '/api/wigle/search-api/saved-ssid-terms',
    method: 'GET',
    requiresAuth: true,
  },
  {
    category: 'WiGLE',
    label: 'Add Saved SSID Term',
    path: '/api/wigle/search-api/saved-ssid-terms',
    method: 'POST',
    requiresAuth: true,
    defaultBody: '{\n  "term": ""\n}',
  },
  {
    category: 'WiGLE',
    label: 'Delete Saved SSID Term',
    path: '/api/wigle/search-api/saved-ssid-terms/:id',
    method: 'DELETE',
    requiresAuth: true,
    params: [{ name: 'id', label: 'Term ID', placeholder: '1', type: 'number' }],
  },
  {
    category: 'WiGLE',
    label: 'V3 Enrichment Stats',
    path: '/api/wigle/enrichment/stats',
    method: 'GET',
    requiresAuth: true,
  },
  {
    category: 'WiGLE',
    label: 'V3 Enrichment Start',
    path: '/api/wigle/enrichment/start',
    method: 'POST',
    requiresAuth: true,
  },
  {
    category: 'WiGLE',
    label: 'V3 Enrichment Resume',
    path: '/api/wigle/enrichment/resume/:runId',
    method: 'POST',
    requiresAuth: true,
    params: [{ name: 'runId', label: 'Run ID', placeholder: '1', type: 'number' }],
  },
  {
    category: 'WiGLE',
    label: 'V3 Enrichment Force-Clear Stuck Run',
    path: '/api/wigle/enrichment/force-clear/:runId',
    method: 'POST',
    requiresAuth: true,
    params: [{ name: 'runId', label: 'Run ID', placeholder: '116', type: 'number' }],
  },
  {
    category: 'WiGLE',
    label: 'WiGLE Import v3',
    path: '/api/wigle/import/v3',
    method: 'POST',
    requiresAuth: true,
    defaultBody: '{\n  "netid": "00:11:22:33:44:55"\n}',
  },
  {
    category: 'WiGLE',
    label: 'Aggregated Observations',
    description:
      'Zoom-aware spatial aggregation across active sources. Returns GeoJSON FeatureCollection of grid-cell centroids.',
    path: '/api/wigle/observations/aggregated',
    method: 'GET',
    params: [
      { name: 'west', label: 'West', defaultValue: '-125', type: 'number' },
      { name: 'south', label: 'South', defaultValue: '24', type: 'number' },
      { name: 'east', label: 'East', defaultValue: '-66', type: 'number' },
      { name: 'north', label: 'North', defaultValue: '50', type: 'number' },
      { name: 'zoom', label: 'Zoom', defaultValue: '5', type: 'number' },
      {
        name: 'sources',
        label: 'Sources',
        defaultValue: 'wigle-v2,wigle-v3,field,kml',
        placeholder: 'wigle-v2,wigle-v3,field,kml',
      },
    ],
  },
  {
    category: 'WiGLE',
    label: 'Observations Extent',
    description:
      'Returns ST_Extent bounding box across active sources. Used by the Fit Bounds button to fly the map to data.',
    path: '/api/wigle/observations/extent',
    method: 'GET',
    params: [
      {
        name: 'sources',
        label: 'Sources',
        defaultValue: 'wigle-v2,wigle-v3,field,kml',
        placeholder: 'wigle-v2,wigle-v3,field,kml',
      },
    ],
  },

  {
    category: 'WiGLE',
    label: 'KML BSSID Summary',
    description:
      'Aggregate kml_points stats for a single BSSID — observation count, first/last seen, timespan days.',
    path: '/api/wigle/kml-bssid-summary',
    method: 'GET',
    params: [{ name: 'bssid', label: 'BSSID', placeholder: '00:11:22:33:44:55' }],
  },

  // ── Machine Learning ──────────────────────────────────────────────────────
  { category: 'Machine Learning', label: 'ML Status', path: '/api/ml/status', method: 'GET' },
  {
    category: 'Machine Learning',
    label: 'ML Score All',
    path: '/api/ml/score-all',
    method: 'POST',
    requiresAuth: true,
    params: [
      { name: 'limit', label: 'Limit', defaultValue: '100', type: 'number' },
      {
        name: 'overwrite_final',
        label: 'Overwrite?',
        defaultValue: 'true',
        type: 'select',
        options: ['true', 'false'],
      },
    ],
    defaultBody: '{\n  "limit": 100,\n  "overwrite_final": true\n}',
  },
  {
    category: 'Machine Learning',
    label: 'ML Train',
    path: '/api/ml/train',
    method: 'POST',
    requiresAuth: true,
    defaultBody: '{\n  "limit": 1000\n}',
  },
  {
    category: 'Machine Learning',
    label: 'ML Scores by BSSID',
    path: '/api/ml/scores/:bssid',
    method: 'GET',
    params: [{ name: 'bssid', label: 'BSSID', placeholder: '00:11:22:33:44:55' }],
  },
  {
    category: 'Machine Learning',
    label: 'ML Scores by Level',
    path: '/api/ml/scores/level/:level',
    method: 'GET',
    params: [
      {
        name: 'level',
        label: 'Level',
        defaultValue: 'high',
        type: 'select',
        options: ['critical', 'high', 'medium', 'low', 'none'],
      },
    ],
  },

  // ── Kepler ────────────────────────────────────────────────────────────────
  {
    category: 'Kepler',
    label: 'Kepler Data',
    path: '/api/kepler/data',
    method: 'GET',
    params: [
      { name: 'limit', label: 'Limit', placeholder: 'no default cap' },
      { name: 'filters', label: 'Filters (JSON)', defaultValue: '{}' },
    ],
  },
  {
    category: 'Kepler',
    label: 'Kepler Observations',
    path: '/api/kepler/observations',
    method: 'GET',
    params: [
      { name: 'limit', label: 'Limit', placeholder: 'no default cap' },
      { name: 'filters', label: 'Filters (JSON)', defaultValue: '{}' },
    ],
  },
  {
    category: 'Kepler',
    label: 'Kepler Networks',
    path: '/api/kepler/networks',
    method: 'GET',
    params: [
      { name: 'limit', label: 'Limit', placeholder: 'no default cap' },
      { name: 'filters', label: 'Filters (JSON)', defaultValue: '{}' },
    ],
  },

  // ── Exports ───────────────────────────────────────────────────────────────
  {
    category: 'Exports',
    label: 'Export CSV',
    path: '/api/csv',
    method: 'GET',
    params: [{ name: 'limit', label: 'Limit', defaultValue: '100' }],
  },
  { category: 'Exports', label: 'Export JSON', path: '/api/json', method: 'GET' },
  { category: 'Exports', label: 'Export Full JSON', path: '/api/json/full', method: 'GET' },
  { category: 'Exports', label: 'Export GeoJSON', path: '/api/geojson', method: 'GET' },
  { category: 'Exports', label: 'Export KML', path: '/api/kml', method: 'GET' },

  // ── Admin Import ──────────────────────────────────────────────────────────
  {
    category: 'Admin Import',
    label: 'Import History',
    path: '/api/admin/import-history',
    method: 'GET',
    requiresAuth: true,
  },
  {
    category: 'Admin Import',
    label: 'Device Sources',
    path: '/api/admin/device-sources',
    method: 'GET',
    requiresAuth: true,
  },
  {
    category: 'Admin Import',
    label: 'Orphan Networks',
    path: '/api/admin/orphan-networks',
    method: 'GET',
    requiresAuth: true,
    params: [
      { name: 'limit', label: 'Limit', defaultValue: '100', type: 'number' },
      { name: 'offset', label: 'Offset', defaultValue: '0', type: 'number' },
      { name: 'search', label: 'Search', placeholder: 'SSID/BSSID' },
      { name: 'sortBy', label: 'Sort By', placeholder: 'moved_at,bssid,observations_imported' },
      { name: 'sortDir', label: 'Sort Dir', placeholder: 'desc,asc' },
    ],
  },
  {
    category: 'Admin Import',
    label: 'Orphan Check WiGLE',
    path: '/api/admin/orphan-networks/:bssid/check-wigle',
    method: 'POST',
    requiresAuth: true,
    params: [{ name: 'bssid', label: 'BSSID', placeholder: '00:11:22:33:44:55' }],
  },
  {
    category: 'Admin Import',
    label: 'Import SQLite',
    description: 'Upload a WiGLE SQLite database file for import.',
    path: '/api/admin/import-sqlite',
    method: 'POST',
    requiresAuth: true,
  },
  {
    category: 'Admin Import',
    label: 'Import SQL',
    description: 'Upload a SQL dump file for import.',
    path: '/api/admin/import-sql',
    method: 'POST',
    requiresAuth: true,
  },
  {
    category: 'Admin Import',
    label: 'Import KML',
    description: 'Upload KML file(s) for import.',
    path: '/api/admin/import-kml',
    method: 'POST',
    requiresAuth: true,
  },
  {
    category: 'Admin Import',
    label: 'Import WiGLE (legacy)',
    path: '/api/import/wigle',
    method: 'POST',
    requiresAuth: true,
  },

  // ── Admin System ──────────────────────────────────────────────────────────
  {
    category: 'Admin System',
    label: 'Admin Test',
    path: '/api/admin/test',
    method: 'GET',
    requiresAuth: true,
  },
  {
    category: 'Admin System',
    label: 'Admin Runtime Settings',
    path: '/api/admin/settings/runtime',
    method: 'GET',
    requiresAuth: true,
  },
  {
    category: 'Admin System',
    label: 'Admin Jobs Status',
    path: '/api/admin/settings/jobs/status',
    method: 'GET',
    requiresAuth: true,
  },
  {
    category: 'Admin System',
    label: 'Admin DB Stats',
    path: '/api/admin/db-stats',
    method: 'GET',
    requiresAuth: true,
  },
  {
    category: 'Admin System',
    label: 'PgAdmin Status',
    path: '/api/admin/pgadmin/status',
    method: 'GET',
    requiresAuth: true,
  },
  {
    category: 'Admin System',
    label: 'Geocoding Stats',
    path: '/api/admin/geocoding/stats',
    method: 'GET',
    requiresAuth: true,
  },
  {
    category: 'Admin System',
    label: 'Geocoding Daemon',
    path: '/api/admin/geocoding/daemon',
    method: 'GET',
    requiresAuth: true,
  },
  {
    category: 'Admin System',
    label: 'Backup Inventory (S3)',
    path: '/api/admin/backup/s3',
    method: 'GET',
    requiresAuth: true,
  },
  {
    category: 'Admin System',
    label: 'AWS Overview',
    path: '/api/admin/aws/overview',
    method: 'GET',
    requiresAuth: true,
  },
  {
    category: 'Admin System',
    label: 'Admin Users',
    path: '/api/admin/users',
    method: 'GET',
    requiresAuth: true,
  },
  {
    category: 'Admin System',
    label: 'Create User',
    path: '/api/admin/users',
    method: 'POST',
    requiresAuth: true,
    defaultBody: '{\n  "username": "",\n  "password": "",\n  "role": "user"\n}',
  },
  {
    category: 'Admin System',
    label: 'Set User Active',
    path: '/api/admin/users/:id/active',
    method: 'PUT',
    requiresAuth: true,
    params: [{ name: 'id', label: 'User ID', placeholder: '1', type: 'number' }],
    defaultBody: '{\n  "active": true\n}',
  },
  {
    category: 'Admin System',
    label: 'Set User Password',
    path: '/api/admin/users/:id/password',
    method: 'PUT',
    requiresAuth: true,
    params: [{ name: 'id', label: 'User ID', placeholder: '1', type: 'number' }],
    defaultBody: '{\n  "password": ""\n}',
  },
  {
    category: 'Admin System',
    label: 'Run Backup',
    path: '/api/admin/backup',
    method: 'POST',
    requiresAuth: true,
  },
  {
    category: 'Admin System',
    label: 'Delete S3 Backup',
    path: '/api/admin/backup/s3/:key',
    method: 'DELETE',
    requiresAuth: true,
    params: [{ name: 'key', label: 'S3 Key', placeholder: 'backups/shadowcheck_20260101.dump' }],
  },
  {
    category: 'Admin System',
    label: 'Start Geocoding Daemon',
    path: '/api/admin/geocoding/daemon',
    method: 'POST',
    requiresAuth: true,
  },
  {
    category: 'Admin System',
    label: 'Stop Geocoding Daemon',
    path: '/api/admin/geocoding/daemon',
    method: 'DELETE',
    requiresAuth: true,
  },
  {
    category: 'Admin System',
    label: 'Run Geocoding',
    path: '/api/admin/geocoding/run',
    method: 'POST',
    requiresAuth: true,
  },
  {
    category: 'Admin System',
    label: 'Test Geocoding',
    path: '/api/admin/geocoding/test',
    method: 'POST',
    requiresAuth: true,
    defaultBody: '{\n  "address": "1600 Pennsylvania Ave NW, Washington DC"\n}',
  },
  {
    category: 'Admin System',
    label: 'Requeue Geocoding',
    path: '/api/admin/geocoding/requeue',
    method: 'POST',
    requiresAuth: true,
  },
  {
    category: 'Admin System',
    label: 'PgAdmin Start',
    path: '/api/admin/pgadmin/start',
    method: 'POST',
    requiresAuth: true,
  },
  {
    category: 'Admin System',
    label: 'PgAdmin Stop',
    path: '/api/admin/pgadmin/stop',
    method: 'POST',
    requiresAuth: true,
  },
  {
    category: 'Admin System',
    label: 'PgAdmin Destroy',
    path: '/api/admin/pgadmin/destroy',
    method: 'POST',
    requiresAuth: true,
  },
  {
    category: 'Admin System',
    label: 'Admin Settings List',
    path: '/api/admin/settings/',
    method: 'GET',
    requiresAuth: true,
  },
  {
    category: 'Admin System',
    label: 'Admin Setting Get',
    path: '/api/admin/settings/:key',
    method: 'GET',
    requiresAuth: true,
    params: [{ name: 'key', label: 'Key', placeholder: 'enable_background_jobs' }],
  },
  {
    category: 'Admin System',
    label: 'Admin Setting Set',
    path: '/api/admin/settings/:key',
    method: 'PUT',
    requiresAuth: true,
    params: [{ name: 'key', label: 'Key', placeholder: 'enable_background_jobs' }],
    defaultBody: '{\n  "value": "true"\n}',
  },
  {
    category: 'Admin System',
    label: 'Run Job Now',
    path: '/api/admin/settings/jobs/:jobName/run',
    method: 'POST',
    requiresAuth: true,
    params: [
      {
        name: 'jobName',
        label: 'Job',
        defaultValue: 'mvRefresh',
        type: 'select',
        options: ['mvRefresh', 'mlScoring', 'backup', 'siblingDetection', 'surveillanceScan'],
      },
    ],
  },
  {
    category: 'Admin System',
    label: 'Toggle ML Blending',
    path: '/api/admin/settings/ml-blending/toggle',
    method: 'POST',
    requiresAuth: true,
  },
  {
    category: 'Admin System',
    label: 'Secrets List',
    path: '/api/admin/secrets',
    method: 'GET',
    requiresAuth: true,
  },
  {
    category: 'Admin System',
    label: 'Secret Set',
    path: '/api/admin/secrets/:key',
    method: 'POST',
    requiresAuth: true,
    params: [{ name: 'key', label: 'Key', placeholder: 'mapbox_token' }],
    defaultBody: '{\n  "value": ""\n}',
  },
  {
    category: 'Admin System',
    label: 'Secret Delete',
    path: '/api/admin/secrets/:key',
    method: 'DELETE',
    requiresAuth: true,
    params: [{ name: 'key', label: 'Key', placeholder: 'mapbox_token' }],
  },
  {
    category: 'Admin System',
    label: 'Cleanup Duplicates',
    path: '/api/admin/cleanup-duplicates',
    method: 'POST',
    requiresAuth: true,
  },
  {
    category: 'Admin System',
    label: 'Refresh Colocation',
    path: '/api/admin/refresh-colocation',
    method: 'POST',
    requiresAuth: true,
  },
  {
    category: 'Admin System',
    label: 'Network Summary',
    path: '/api/admin/network-summary/:bssid',
    method: 'GET',
    requiresAuth: true,
    params: [{ name: 'bssid', label: 'BSSID', placeholder: '00:11:22:33:44:55' }],
  },
  {
    category: 'Admin System',
    label: 'Check Duplicates',
    path: '/api/observations/check-duplicates/:bssid',
    method: 'GET',
    requiresAuth: true,
    params: [{ name: 'bssid', label: 'BSSID', placeholder: '00:11:22:33:44:55' }],
  },
  {
    category: 'Admin System',
    label: 'AWS Instance Start',
    path: '/api/admin/aws/instances/:instanceId/start',
    method: 'POST',
    requiresAuth: true,
    params: [{ name: 'instanceId', label: 'Instance ID', placeholder: 'i-0123456789abcdef0' }],
  },
  {
    category: 'Admin System',
    label: 'AWS Instance Stop',
    path: '/api/admin/aws/instances/:instanceId/stop',
    method: 'POST',
    requiresAuth: true,
    params: [{ name: 'instanceId', label: 'Instance ID', placeholder: 'i-0123456789abcdef0' }],
  },
  {
    category: 'Admin System',
    label: 'AWS Instance Reboot',
    path: '/api/admin/aws/instances/:instanceId/reboot',
    method: 'POST',
    requiresAuth: true,
    params: [{ name: 'instanceId', label: 'Instance ID', placeholder: 'i-0123456789abcdef0' }],
  },

  // ── Admin Analysis ────────────────────────────────────────────────────────
  {
    category: 'Admin Analysis',
    label: 'Sibling Refresh Status',
    path: '/api/admin/siblings/refresh/status',
    method: 'GET',
    requiresAuth: true,
  },
  {
    category: 'Admin Analysis',
    label: 'Sibling Stats',
    path: '/api/admin/siblings/stats',
    method: 'GET',
    requiresAuth: true,
  },
  {
    category: 'Admin Analysis',
    label: 'Sibling Pairs Purge',
    path: '/api/admin/siblings/pairs',
    method: 'DELETE',
    requiresAuth: true,
  },
  {
    category: 'Admin Analysis',
    label: 'Sibling Linked',
    path: '/api/admin/siblings/linked/:bssid',
    method: 'GET',
    requiresAuth: true,
    params: [{ name: 'bssid', label: 'BSSID', placeholder: '00:11:22:33:44:55' }],
  },
  {
    category: 'Admin Analysis',
    label: 'OUI Groups',
    path: '/api/admin/oui/groups',
    method: 'GET',
    requiresAuth: true,
  },
  {
    category: 'Admin Analysis',
    label: 'OUI Details',
    path: '/api/admin/oui/:oui/details',
    method: 'GET',
    requiresAuth: true,
    params: [{ name: 'oui', label: 'OUI', placeholder: 'AABBCC' }],
  },
  {
    category: 'Admin Analysis',
    label: 'Randomization Suspects',
    path: '/api/admin/oui/randomization/suspects',
    method: 'GET',
    requiresAuth: true,
  },
  {
    category: 'Admin Analysis',
    label: 'OUI Analyze',
    path: '/api/admin/oui/analyze',
    method: 'POST',
    requiresAuth: true,
    defaultBody: '{\n  "oui": "AABBCC"\n}',
  },
  {
    category: 'Admin Analysis',
    label: 'Sibling Override',
    path: '/api/admin/siblings/override',
    method: 'POST',
    requiresAuth: true,
    defaultBody: '{\n  "bssid_a": "00:11:22:33:44:55",\n  "bssid_b": "AA:BB:CC:DD:EE:FF"\n}',
  },
  {
    category: 'Admin Analysis',
    label: 'Sibling Refresh',
    path: '/api/admin/siblings/refresh',
    method: 'POST',
    requiresAuth: true,
  },
  {
    category: 'Admin Analysis',
    label: 'Sibling Linked Batch',
    path: '/api/admin/siblings/linked-batch',
    method: 'POST',
    requiresAuth: true,
    defaultBody: '{\n  "bssids": ["00:11:22:33:44:55"]\n}',
  },
  {
    category: 'Admin Analysis',
    label: 'Detection Evidence',
    path: '/api/admin/networks/:bssid/detection-evidence',
    method: 'GET',
    requiresAuth: true,
    params: [{ name: 'bssid', label: 'BSSID', placeholder: '00:14:3E:4A:67:A0' }],
  },
  {
    category: 'Admin Analysis',
    label: 'Network Media',
    path: '/api/admin/network-media/:bssid',
    method: 'GET',
    requiresAuth: true,
    params: [{ name: 'bssid', label: 'BSSID', placeholder: '00:11:22:33:44:55' }],
  },
  {
    category: 'Admin Analysis',
    label: 'Network Notes (admin)',
    path: '/api/admin/network-notes/:bssid',
    method: 'GET',
    requiresAuth: true,
    params: [{ name: 'bssid', label: 'BSSID', placeholder: '00:11:22:33:44:55' }],
  },
  {
    category: 'Admin Analysis',
    label: 'Network Tags (admin)',
    path: '/api/admin/network-tags/:bssid',
    method: 'GET',
    requiresAuth: true,
    params: [{ name: 'bssid', label: 'BSSID', placeholder: '00:11:22:33:44:55' }],
  },

  // ── Claude / AI ───────────────────────────────────────────────────────────
  {
    category: 'Claude / AI',
    label: 'Analyze Networks',
    path: '/api/claude/analyze-networks',
    method: 'POST',
    requiresAuth: true,
    defaultBody:
      '{\n  "networks": [{"bssid":"AA:BB:CC:DD:EE:FF","ssid":"TestNet","threat_score":75}],\n  "question": "Is this a surveillance threat?"\n}',
  },
  {
    category: 'Claude / AI',
    label: 'AI Insights',
    path: '/api/claude/insights',
    method: 'GET',
    requiresAuth: true,
  },
  {
    category: 'Claude / AI',
    label: 'Mark Insight Useful',
    path: '/api/claude/insights/:id/useful',
    method: 'PATCH',
    requiresAuth: true,
    params: [{ name: 'id', label: 'Insight ID', placeholder: '1', type: 'number' }],
    defaultBody: '{\n  "useful": true\n}',
  },
  {
    category: 'Claude / AI',
    label: 'Claude Test',
    path: '/api/claude/test',
    method: 'GET',
    requiresAuth: true,
  },

  // ── Sibling Detection ──────────────────────────────────────────────────────
];
